name: Build and Upload macOS Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install Dependencies
      run: |
        pip install pyinstaller
        # You can add any additional dependencies here

    - name: Build Executable
      run: |
        pyinstaller --onefile main.py
        # Replace 'main.py' with your actual script filename

    - name: Upload Executable
      run: |
        zip -r mac_exe.zip dist/main
        # Compress the executable into a zip file
        # Set up your GitHub token (TOKEN) as a secret in your repository
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/zip" \
        --upload-file mac_exe.zip \
        "https://uploads.github.com/repos/MS-Jahan/test-macos-exe/releases/refs/heads/main/assets?name=mac_exe.zip"

